In [56]:
import pandas as pd
import numpy as np
import requests
import io
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
import time
import matplotlib.pyplot as plt

In [58]:
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

In [29]:
url="https://raw.githubusercontent.com/timcsmith/MIS536-Public/master/Data/UniversalBank.csv"
s=requests.get(url).content
bank_df=pd.read_csv(io.StringIO(s.decode('utf-8')))

In [30]:
bank_df=bank_df.drop(['ID', 'ZIP Code'],axis=1)
bank_df.head()
bank_df.columns

Index(['Age', 'Experience', 'Income', 'Family', 'CCAvg', 'Education',
       'Mortgage', 'Personal Loan', 'Securities Account', 'CD Account',
       'Online', 'CreditCard'],
      dtype='object')

In [31]:
bank_df['Education'] = bank_df['Education'].astype('category')
bank_df = pd.get_dummies(bank_df, prefix_sep='_', drop_first=False)
X=band_df.drop(['Personal Loan'],axis=1)
y=band_df.iloc[:,6]
train_X, valid_X, train_y, valid_y = train_test_split(X, y, test_size=.2, random_state=1)

In [35]:
%%time
start = time.time()

model = MLPClassifier(hidden_layer_sizes=(500,250,100,40), solver='adam', max_iter=200, verbose=True)
model.fit(train_X, train_y)
end = time.time()
print("Total Time", end - start)

Iteration 1, loss = 1.08385594
Iteration 2, loss = 0.65032350
Iteration 3, loss = 0.60803424
Iteration 4, loss = 0.56650923
Iteration 5, loss = 0.53082751
Iteration 6, loss = 0.45428297
Iteration 7, loss = 0.34922108
Iteration 8, loss = 0.27548017
Iteration 9, loss = 0.19756099
Iteration 10, loss = 0.15494463
Iteration 11, loss = 0.17223990
Iteration 12, loss = 0.16230835
Iteration 13, loss = 0.06798807
Iteration 14, loss = 0.04825004
Iteration 15, loss = 0.23558385
Iteration 16, loss = 0.08397793
Iteration 17, loss = 0.03313571
Iteration 18, loss = 0.04469418
Iteration 19, loss = 0.06436815
Iteration 20, loss = 0.03636675
Iteration 21, loss = 0.02868491
Iteration 22, loss = 0.01010003
Iteration 23, loss = 0.00612952
Iteration 24, loss = 0.02110479
Iteration 25, loss = 0.00631741
Iteration 26, loss = 0.00148415
Iteration 27, loss = 0.00097886
Iteration 28, loss = 0.00073633
Iteration 29, loss = 0.00057049
Iteration 30, loss = 0.00038658
Iteration 31, loss = 0.00068694
Iteration 32, los

In [36]:
start = time.time()
print(model.predict(valid_X))
end = time.time()
print("Total Time", end - start)

[1 0 0 0 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 1 0 1 0 0
 1 0 1 0 0 1 0 0 0 0 1 1 0 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0
 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 1 0 0 1 0 1 1 1 0
 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0 0 1 0 0 0 1 0 0 0 0
 1 0 1 0 1 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1
 1 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 0 0 0 1 1 1 0
 0 0 0 0 0 1 1 0 1 0 0 1 0 0 1 1 0 0 1 0 0 1 0 1 0 1 1 1 0 0 1 0 0 1 0 0 1
 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0
 0 0 0 1 0 1 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1
 0 0 1 0 0 0 1 0 1 0 1 1 1 0 1 0 1 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 1 0
 0 0 1 0 0 0 0 1 1 1 0 0 1 0 0 0 1 1 0 1 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 1 1 0 0
 0 1 1 1 0 0 1 0 0 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0
 0 0 0 0 0 0 0 1 1 0 0 0 

In [40]:
start = time.time()
validation_predictions = model.predict(valid_X)
end = time.time()
print("Total Time per prediction =", (end - start)/len(valid_X))


print('Accuracy Score: ', accuracy_score(valid_y, validation_predictions))
print('Precision Score: ', precision_score(valid_y, validation_predictions))
print('Recall Score: ', recall_score(valid_y, validation_predictions))
print(confusion_matrix(validation_predictions,valid_y))

Total Time per prediction = 3.0997991561889645e-05
Accuracy Score:  1.0
Precision Score:  1.0
Recall Score:  1.0
[[715   0]
 [  0 285]]


In [41]:
# I am not sure if this actually worked as accuracy,precision and recall of 1.0 is unexpected
# Evidently confusion matrix is showing that accuracy precision are correct

In [45]:
%%time
start = time.time()

model = MLPClassifier(hidden_layer_sizes=(100), solver='adam', max_iter=100, verbose=True)
model.fit(train_X, train_y)
end = time.time()
print("Total Time", end - start)

Iteration 1, loss = 1.78387872
Iteration 2, loss = 0.85447552
Iteration 3, loss = 0.64148656
Iteration 4, loss = 0.56973635
Iteration 5, loss = 0.52665623
Iteration 6, loss = 0.49888486
Iteration 7, loss = 0.47060186
Iteration 8, loss = 0.44163249
Iteration 9, loss = 0.41311744
Iteration 10, loss = 0.38274062
Iteration 11, loss = 0.34586397
Iteration 12, loss = 0.31125106
Iteration 13, loss = 0.28195135
Iteration 14, loss = 0.26202648
Iteration 15, loss = 0.23012849
Iteration 16, loss = 0.20804698
Iteration 17, loss = 0.18736078
Iteration 18, loss = 0.17019991
Iteration 19, loss = 0.15510511
Iteration 20, loss = 0.13732848
Iteration 21, loss = 0.12375286
Iteration 22, loss = 0.11094421
Iteration 23, loss = 0.10164733
Iteration 24, loss = 0.09189040
Iteration 25, loss = 0.08422954
Iteration 26, loss = 0.07671426
Iteration 27, loss = 0.07292293
Iteration 28, loss = 0.07028558
Iteration 29, loss = 0.06163401
Iteration 30, loss = 0.05641593
Iteration 31, loss = 0.05086859
Iteration 32, los

In [46]:
start = time.time()
validation_predictions = model.predict(valid_X)
end = time.time()
print("Total Time per prediction =", (end - start)/len(valid_X))


print('Accuracy Score: ', accuracy_score(valid_y, validation_predictions))
print('Precision Score: ', precision_score(valid_y, validation_predictions))
print('Recall Score: ', recall_score(valid_y, validation_predictions))
print(confusion_matrix(validation_predictions,valid_y))

Total Time per prediction = 5.9967041015625e-06
Accuracy Score:  1.0
Precision Score:  1.0
Recall Score:  1.0
[[715   0]
 [  0 285]]


In [52]:
%%time
start = time.time()

model = MLPClassifier(hidden_layer_sizes=(10,15,20,5,3), solver='adam', max_iter=200, verbose=True)
model.fit(train_X, train_y)
end = time.time()
print("Total Time", end - start)

Iteration 1, loss = 1.79612222
Iteration 2, loss = 0.80797544
Iteration 3, loss = 0.62296179
Iteration 4, loss = 0.61020097
Iteration 5, loss = 0.61004171
Iteration 6, loss = 0.60991697
Iteration 7, loss = 0.60978392
Iteration 8, loss = 0.60963165
Iteration 9, loss = 0.60949624
Iteration 10, loss = 0.60937300
Iteration 11, loss = 0.60922375
Iteration 12, loss = 0.60910323
Iteration 13, loss = 0.60897489
Iteration 14, loss = 0.60886363
Iteration 15, loss = 0.60876457
Iteration 16, loss = 0.60865709
Iteration 17, loss = 0.60854925
Iteration 18, loss = 0.60847690
Iteration 19, loss = 0.60838291
Iteration 20, loss = 0.60830378
Iteration 21, loss = 0.60823834
Iteration 22, loss = 0.60817682
Iteration 23, loss = 0.60812296
Iteration 24, loss = 0.60805954
Iteration 25, loss = 0.60801580
Iteration 26, loss = 0.60797079
Iteration 27, loss = 0.60793746
Iteration 28, loss = 0.60790127
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.
Total Time 0.9039962291

In [53]:
start = time.time()
validation_predictions = model.predict(valid_X)
end = time.time()
print("Total Time per prediction =", (end - start)/len(valid_X))


print('Accuracy Score: ', accuracy_score(valid_y, validation_predictions))
print('Precision Score: ', precision_score(valid_y, validation_predictions))
print('Recall Score: ', recall_score(valid_y, validation_predictions))
print(confusion_matrix(validation_predictions,valid_y))

Total Time per prediction = 4.997014999389648e-06
Accuracy Score:  0.715
Precision Score:  0.0
Recall Score:  0.0
[[715 285]
 [  0   0]]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [49]:
# looking at all three combinations it is evident that having more neurons in this case matters more than having 
# more layers. Last one specifically was example of that

In [54]:
# First combination of 4 hidden layers 
#Total Time per prediction = 3.0997991561889645e-05
#Accuracy Score:  1.0
#Precision Score:  1.0
#Recall Score:  1.0
#[[715   0]
# [  0 285]]

#Second combo with only one hidden layer with 100 neurons
#Total Time per prediction = 5.9967041015625e-06
#Accuracy Score:  1.0
#Precision Score:  1.0
#Recall Score:  1.0
#[[715   0]
# [  0 285]]

# third combo with five hidden layers
#Total Time per prediction = 4.997014999389648e-06
#Accuracy Score:  0.715
#Precision Score:  0.0
#Recall Score:  0.0
#[[715 285]
# [  0   0]]


In [55]:
# K-NN model

In [81]:
start = time.time()
neigh=np.linspace(1,50,50)
neigh=list(neigh)
neigh=[int(i) for i in neigh]
p=np.linspace(1,10,10)
p=list(neigh)
p=[int(i) for i in neigh]
param_grid={'n_neighbors':neigh,
           'p':p,
            'weights':['uniform', 'distance']}
gridSearch = GridSearchCV(estimator = KNeighborsClassifier(), param_grid=param_grid, cv = 3, verbose=2,  n_jobs = -1)
gridSearch.fit(train_X, train_y)
bestGridModel = gridSearch.best_estimator_
print('Best parameters found: ', gridSearch.best_params_)
end = time.time()
print("Total Time =", (end - start))

Fitting 3 folds for each of 5000 candidates, totalling 15000 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    2.1s
[Parallel(n_jobs=-1)]: Done 504 tasks      | elapsed:   11.9s
[Parallel(n_jobs=-1)]: Done 1316 tasks      | elapsed:   30.2s
[Parallel(n_jobs=-1)]: Done 2448 tasks      | elapsed:   52.6s
[Parallel(n_jobs=-1)]: Done 3908 tasks      | elapsed:  1.4min
[Parallel(n_jobs=-1)]: Done 5688 tasks      | elapsed:  2.1min
[Parallel(n_jobs=-1)]: Done 7796 tasks      | elapsed:  2.9min
[Parallel(n_jobs=-1)]: Done 10224 tasks      | elapsed:  3.8min
[Parallel(n_jobs=-1)]: Done 12980 tasks      | elapsed:  4.9min


Best parameters found:  {'n_neighbors': 6, 'p': 1, 'weights': 'distance'}
Total Time = 344.68347358703613


[Parallel(n_jobs=-1)]: Done 14993 out of 15000 | elapsed:  5.7min remaining:    0.1s
[Parallel(n_jobs=-1)]: Done 15000 out of 15000 | elapsed:  5.7min finished


In [86]:
start = time.time()
validation_predictions = bestGridModel.predict(valid_X)
end = time.time()
print("Total Time per prediction =", (end - start)/len(valid_X))
print(accuracy_score(valid_y, validation_predictions))
print(precision_score(valid_y, validation_predictions))
print(recall_score(valid_y, validation_predictions))
print(confusion_matrix(validation_predictions,valid_y))

Total Time per prediction = 1.0998010635375976e-05
0.876
0.867579908675799
0.6666666666666666
[[686  95]
 [ 29 190]]


In [87]:
# kneghbours classifier did not perform as well as MLP classifier
# Although it did well enough when looking at correct predictions it has made

In [88]:
#compare time taken
#training time:
# Total Time 10.832026720046997 secs ; 4 hidden layers with lot of neurons
#Total Time 2.5610265731811523 sec  ; 1 hidden layer
# Total Time 0.9039962291717529 sec  ; 5 hidden layers with few less neurons
# total time for KNN : 344.68347358703613 sec
# KNN took lot longer time than neural network and one reason with that is gridsearch parameters.
# KNN had 1000 combinations so per combination it would be 34.4 seconds
# Let's try only one combination and see how long it takes

In [92]:
start=time.time()
clf=KNeighborsClassifier(n_neighbors=6,p=1,weights='distance')
clf.fit(train_X, train_y)
end = time.time()
print("Total Time=", (end - start))
print(accuracy_score(valid_y, validation_predictions))
print(precision_score(valid_y, validation_predictions))
print(recall_score(valid_y, validation_predictions))
print(confusion_matrix(validation_predictions,valid_y))

Total Time= 0.016998291015625
0.876
0.867579908675799
0.6666666666666666
[[686  95]
 [ 29 190]]


In [93]:
# time taken is significantly lower now
# Although gridsearch is necessary for this KNN as we don't know prior what combination is perfect.
# So MLP is better for time consumed


In [98]:
# Let's compare time per validation
# Total Time per prediction = 1.0998010635375976e-05          ;KNN
# maximum Total Time per prediction = 3.0997991561889645e-05  ;MLP
# This time is very much comparable and one can't say for sure which one will take less time
# This is because every run I made and repeated gave me different time
# one example is illustrated below

In [99]:
start = time.time()
validation_predictions = bestGridModel.predict(valid_X)
end = time.time()
print("Total Time per prediction =", (end - start)/len(valid_X))

Total Time per prediction = 8.03232192993164e-06


In [100]:
# So all things considered MLP is much better for time consumptions and accuracy is very high as well
# I would recommend this model 
# Although I read some amount on tensorflow models which are better than scikitlearn if model is available 
# And tensorflow has GPU capabilities which will improve calculation time and ne can train huge data and 
# can use more neurons and layers without losing lot of time